apiVersion: v1
kind: Service
metadata:
  name: borcelle-crm-service
spec:
  selector:
    app: borcelle-crm
  ports:
    - protocol: TCP
      port: 8014
      targetPort: 8014
      nodePort: 32014
  type: NodePort