apiVersion: v1
kind: Service
metadata:
  name: borcelle-crm-service
spec:
  selector:
    app: borcelle-crm
  ports:
    - name: uvicorn
      protocol: TCP
      port: 8014
      targetPort: 8014
      nodePort: 32014
    - name: celery-flower
      protocol: TCP
      port: 8052
      targetPort: 8052
      nodePort: 32052
  type: NodePort
